name: JPlugin
version: 1.0
author: Janakthegamer
main: com.janakthegamer.jplugin.JPlugin
api-version: 1.17

commands:
  heal:
    description: Maxout your health
    usage: /<command>

  feed:
    description: Maxout your hunger
    usage: /<command>

  farmtime:
    description: Spawn Entitiy
    usage: /<command>

  givewand:
    description: Get a Special wand
    usage: /<command>